//===USER===
export const GET_USER = "GET_USER";
export const USER_LOGIN = "USER_LOGIN";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOADING = "LOADING";
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "GET_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_USER_BY_USERNAME = "GET_USER_BY_USERNAME";
export const SEND_FORGOT_PASSWORD_EMAIL = "SEND_FORGOT_PASSWORD_EMAIL";
export const SEND_FORGOT_PASSWORD_EMAIL_ERROR =
  "SEND_FORGOT_PASSWORD_EMAIL_ERROR";
export const CONFIRMATION_CODE_ERROR = "CONFIRMATION_CODE_ERROR";
export const CANCEL_FORGOT_PASSWORD = "CANCEL_FORGOT_PASSWORD";
export const CONFIRMATION_CODE_SUCCESS = "CONFIRMATION_CODE_SUCCESS";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERRROR";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const USER_ADD_PROFILE_PHOTO = "USER_ADD_PROFILE_PHOTO";
export const REMOVE_PROFILE_PHOTO = "REMOVE_PROFILE_PHOTO";
//===USER===

//===SELLER===
export const SELLER_REGISTER = "SELLER_REGISTER";
export const SELLER_LOADING = "SELLER_LOADING";
export const SELLER_LOGIN = "SELLER_LOGIN";
export const SELLER_ERROR = "SELLER_ERROR";
export const SELLER_LOGOUT = "SELLER_LOGOUT";
export const GET_CURRENT_SELLER = "GET_CURRENT_SELLER";
export const SELLER_SEND_FORGOT_PASSWORD_EMAIL =
  "SELLER_SEND_FORGOT_PASSWORD_EMAIL";
export const SELLER_CHECK_PASSWORD_TOKEN = "SELLER_CHECK_PASSWORD_TOKEN";
export const SELLER_CHANGE_PASSWORD = "SELLER_CHANGE_PASSWORD";
export const SELLER_RESET_PASSWORD_TOKEN_ERROR =
  "SELLER_RESET_PASSWORD_TOKEN_ERROR";
export const SELLER_RESET_PASSWORD_ERROR = "SELLER_RESET_PASSWORD_ERROR";
//===SELLER===
