export const GET_USER = "GET_USER";
export const USER_LOGIN = "USER_LOGIN";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOADING = "LOADING";
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "GET_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_USER_BY_USERNAME = "GET_USER_BY_USERNAME";
export const SEND_FORGOT_PASSWORD_EMAIL = "SEND_FORGOT_PASSWORD_EMAIL";
export const SEND_FORGOT_PASSWORD_EMAIL_ERROR =
  "SEND_FORGOT_PASSWORD_EMAIL_ERROR";
export const CONFIRMATION_CODE_ERROR = "CONFIRMATION_CODE_ERROR";
export const CANCEL_FORGOT_PASSWORD = "CANCEL_FORGOT_PASSWORD";
export const CONFIRMATION_CODE_SUCCESS = "CONFIRMATION_CODE_SUCCESS";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERRROR";
